# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_plc_swig', [dirname(__file__)])
        except ImportError:
            import _plc_swig
            return _plc_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_plc_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _plc_swig = swig_import_helper()
    del swig_import_helper
else:
    import _plc_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _plc_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _plc_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _plc_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _plc_swig.high_res_timer_epoch()
class plcp_transmit(object):
    """Proxy of C++ gr::plc::plcp_transmit class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(debug=False):
        """make(bool debug=False) -> plcp_transmit_sptr"""
        return _plc_swig.plcp_transmit_make(debug)

    make = staticmethod(make)
    __swig_destroy__ = _plc_swig.delete_plcp_transmit
    __del__ = lambda self : None;
plcp_transmit_swigregister = _plc_swig.plcp_transmit_swigregister
plcp_transmit_swigregister(plcp_transmit)

def plcp_transmit_make(debug=False):
  """plcp_transmit_make(bool debug=False) -> plcp_transmit_sptr"""
  return _plc_swig.plcp_transmit_make(debug)

class plcp_transmit_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::plc::plcp_transmit)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::plc::plcp_transmit)> self) -> plcp_transmit_sptr
        __init__(boost::shared_ptr<(gr::plc::plcp_transmit)> self, plcp_transmit p) -> plcp_transmit_sptr
        """
        this = _plc_swig.new_plcp_transmit_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(plcp_transmit_sptr self) -> plcp_transmit"""
        return _plc_swig.plcp_transmit_sptr___deref__(self)

    __swig_destroy__ = _plc_swig.delete_plcp_transmit_sptr
    __del__ = lambda self : None;
    def make(self, debug=False):
        """make(plcp_transmit_sptr self, bool debug=False) -> plcp_transmit_sptr"""
        return _plc_swig.plcp_transmit_sptr_make(self, debug)

    def history(self):
        """history(plcp_transmit_sptr self) -> unsigned int"""
        return _plc_swig.plcp_transmit_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(plcp_transmit_sptr self, int which, int delay)
        declare_sample_delay(plcp_transmit_sptr self, unsigned int delay)
        """
        return _plc_swig.plcp_transmit_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(plcp_transmit_sptr self, int which) -> unsigned int"""
        return _plc_swig.plcp_transmit_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(plcp_transmit_sptr self) -> int"""
        return _plc_swig.plcp_transmit_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(plcp_transmit_sptr self) -> double"""
        return _plc_swig.plcp_transmit_sptr_relative_rate(self)

    def start(self):
        """start(plcp_transmit_sptr self) -> bool"""
        return _plc_swig.plcp_transmit_sptr_start(self)

    def stop(self):
        """stop(plcp_transmit_sptr self) -> bool"""
        return _plc_swig.plcp_transmit_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(plcp_transmit_sptr self, unsigned int which_input) -> uint64_t"""
        return _plc_swig.plcp_transmit_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(plcp_transmit_sptr self, unsigned int which_output) -> uint64_t"""
        return _plc_swig.plcp_transmit_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(plcp_transmit_sptr self) -> int"""
        return _plc_swig.plcp_transmit_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(plcp_transmit_sptr self, int m)"""
        return _plc_swig.plcp_transmit_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(plcp_transmit_sptr self)"""
        return _plc_swig.plcp_transmit_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(plcp_transmit_sptr self) -> bool"""
        return _plc_swig.plcp_transmit_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(plcp_transmit_sptr self, int m)"""
        return _plc_swig.plcp_transmit_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(plcp_transmit_sptr self) -> int"""
        return _plc_swig.plcp_transmit_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(plcp_transmit_sptr self, int i) -> long"""
        return _plc_swig.plcp_transmit_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(plcp_transmit_sptr self, long max_output_buffer)
        set_max_output_buffer(plcp_transmit_sptr self, int port, long max_output_buffer)
        """
        return _plc_swig.plcp_transmit_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(plcp_transmit_sptr self, int i) -> long"""
        return _plc_swig.plcp_transmit_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(plcp_transmit_sptr self, long min_output_buffer)
        set_min_output_buffer(plcp_transmit_sptr self, int port, long min_output_buffer)
        """
        return _plc_swig.plcp_transmit_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(plcp_transmit_sptr self, int which) -> float
        pc_input_buffers_full(plcp_transmit_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_transmit_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(plcp_transmit_sptr self, int which) -> float
        pc_input_buffers_full_avg(plcp_transmit_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_transmit_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(plcp_transmit_sptr self, int which) -> float
        pc_input_buffers_full_var(plcp_transmit_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_transmit_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(plcp_transmit_sptr self, int which) -> float
        pc_output_buffers_full(plcp_transmit_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_transmit_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(plcp_transmit_sptr self, int which) -> float
        pc_output_buffers_full_avg(plcp_transmit_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_transmit_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(plcp_transmit_sptr self, int which) -> float
        pc_output_buffers_full_var(plcp_transmit_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_transmit_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(plcp_transmit_sptr self) -> float"""
        return _plc_swig.plcp_transmit_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(plcp_transmit_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _plc_swig.plcp_transmit_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(plcp_transmit_sptr self)"""
        return _plc_swig.plcp_transmit_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(plcp_transmit_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _plc_swig.plcp_transmit_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(plcp_transmit_sptr self) -> int"""
        return _plc_swig.plcp_transmit_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(plcp_transmit_sptr self) -> int"""
        return _plc_swig.plcp_transmit_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(plcp_transmit_sptr self, int priority) -> int"""
        return _plc_swig.plcp_transmit_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(plcp_transmit_sptr self) -> std::string"""
        return _plc_swig.plcp_transmit_sptr_name(self)

    def symbol_name(self):
        """symbol_name(plcp_transmit_sptr self) -> std::string"""
        return _plc_swig.plcp_transmit_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(plcp_transmit_sptr self) -> io_signature_sptr"""
        return _plc_swig.plcp_transmit_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(plcp_transmit_sptr self) -> io_signature_sptr"""
        return _plc_swig.plcp_transmit_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(plcp_transmit_sptr self) -> long"""
        return _plc_swig.plcp_transmit_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(plcp_transmit_sptr self) -> basic_block_sptr"""
        return _plc_swig.plcp_transmit_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(plcp_transmit_sptr self, int ninputs, int noutputs) -> bool"""
        return _plc_swig.plcp_transmit_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(plcp_transmit_sptr self) -> std::string"""
        return _plc_swig.plcp_transmit_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(plcp_transmit_sptr self, std::string name)"""
        return _plc_swig.plcp_transmit_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(plcp_transmit_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _plc_swig.plcp_transmit_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(plcp_transmit_sptr self) -> swig_int_ptr"""
        return _plc_swig.plcp_transmit_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(plcp_transmit_sptr self) -> swig_int_ptr"""
        return _plc_swig.plcp_transmit_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(plcp_transmit_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _plc_swig.plcp_transmit_sptr_message_subscribers(self, *args, **kwargs)

plcp_transmit_sptr_swigregister = _plc_swig.plcp_transmit_sptr_swigregister
plcp_transmit_sptr_swigregister(plcp_transmit_sptr)

plcp_transmit_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
plcp_transmit = plcp_transmit.make;

class mac(object):
    """Proxy of C++ gr::plc::mac class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """make(float period_ms, int count) -> mac_sptr"""
        return _plc_swig.mac_make(*args, **kwargs)

    make = staticmethod(make)
    def set_period(self, *args, **kwargs):
        """set_period(mac self, float period_ms)"""
        return _plc_swig.mac_set_period(self, *args, **kwargs)

    def period(self):
        """period(mac self) -> float"""
        return _plc_swig.mac_period(self)

    def set_count(self, *args, **kwargs):
        """set_count(mac self, int count)"""
        return _plc_swig.mac_set_count(self, *args, **kwargs)

    def count(self):
        """count(mac self) -> int"""
        return _plc_swig.mac_count(self)

    __swig_destroy__ = _plc_swig.delete_mac
    __del__ = lambda self : None;
mac_swigregister = _plc_swig.mac_swigregister
mac_swigregister(mac)

def mac_make(*args, **kwargs):
  """mac_make(float period_ms, int count) -> mac_sptr"""
  return _plc_swig.mac_make(*args, **kwargs)

class mac_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::plc::mac)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::plc::mac)> self) -> mac_sptr
        __init__(boost::shared_ptr<(gr::plc::mac)> self, mac p) -> mac_sptr
        """
        this = _plc_swig.new_mac_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(mac_sptr self) -> mac"""
        return _plc_swig.mac_sptr___deref__(self)

    __swig_destroy__ = _plc_swig.delete_mac_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """make(mac_sptr self, float period_ms, int count) -> mac_sptr"""
        return _plc_swig.mac_sptr_make(self, *args, **kwargs)

    def set_period(self, *args, **kwargs):
        """set_period(mac_sptr self, float period_ms)"""
        return _plc_swig.mac_sptr_set_period(self, *args, **kwargs)

    def period(self):
        """period(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_period(self)

    def set_count(self, *args, **kwargs):
        """set_count(mac_sptr self, int count)"""
        return _plc_swig.mac_sptr_set_count(self, *args, **kwargs)

    def count(self):
        """count(mac_sptr self) -> int"""
        return _plc_swig.mac_sptr_count(self)

    def history(self):
        """history(mac_sptr self) -> unsigned int"""
        return _plc_swig.mac_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(mac_sptr self, int which, int delay)
        declare_sample_delay(mac_sptr self, unsigned int delay)
        """
        return _plc_swig.mac_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(mac_sptr self, int which) -> unsigned int"""
        return _plc_swig.mac_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(mac_sptr self) -> int"""
        return _plc_swig.mac_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(mac_sptr self) -> double"""
        return _plc_swig.mac_sptr_relative_rate(self)

    def start(self):
        """start(mac_sptr self) -> bool"""
        return _plc_swig.mac_sptr_start(self)

    def stop(self):
        """stop(mac_sptr self) -> bool"""
        return _plc_swig.mac_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(mac_sptr self, unsigned int which_input) -> uint64_t"""
        return _plc_swig.mac_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(mac_sptr self, unsigned int which_output) -> uint64_t"""
        return _plc_swig.mac_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(mac_sptr self) -> int"""
        return _plc_swig.mac_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(mac_sptr self, int m)"""
        return _plc_swig.mac_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(mac_sptr self)"""
        return _plc_swig.mac_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(mac_sptr self) -> bool"""
        return _plc_swig.mac_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(mac_sptr self, int m)"""
        return _plc_swig.mac_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(mac_sptr self) -> int"""
        return _plc_swig.mac_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(mac_sptr self, int i) -> long"""
        return _plc_swig.mac_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(mac_sptr self, long max_output_buffer)
        set_max_output_buffer(mac_sptr self, int port, long max_output_buffer)
        """
        return _plc_swig.mac_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(mac_sptr self, int i) -> long"""
        return _plc_swig.mac_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(mac_sptr self, long min_output_buffer)
        set_min_output_buffer(mac_sptr self, int port, long min_output_buffer)
        """
        return _plc_swig.mac_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(mac_sptr self, int which) -> float
        pc_input_buffers_full(mac_sptr self) -> pmt_vector_float
        """
        return _plc_swig.mac_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(mac_sptr self, int which) -> float
        pc_input_buffers_full_avg(mac_sptr self) -> pmt_vector_float
        """
        return _plc_swig.mac_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(mac_sptr self, int which) -> float
        pc_input_buffers_full_var(mac_sptr self) -> pmt_vector_float
        """
        return _plc_swig.mac_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(mac_sptr self, int which) -> float
        pc_output_buffers_full(mac_sptr self) -> pmt_vector_float
        """
        return _plc_swig.mac_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(mac_sptr self, int which) -> float
        pc_output_buffers_full_avg(mac_sptr self) -> pmt_vector_float
        """
        return _plc_swig.mac_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(mac_sptr self, int which) -> float
        pc_output_buffers_full_var(mac_sptr self) -> pmt_vector_float
        """
        return _plc_swig.mac_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(mac_sptr self) -> float"""
        return _plc_swig.mac_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(mac_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _plc_swig.mac_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(mac_sptr self)"""
        return _plc_swig.mac_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(mac_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _plc_swig.mac_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(mac_sptr self) -> int"""
        return _plc_swig.mac_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(mac_sptr self) -> int"""
        return _plc_swig.mac_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(mac_sptr self, int priority) -> int"""
        return _plc_swig.mac_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(mac_sptr self) -> std::string"""
        return _plc_swig.mac_sptr_name(self)

    def symbol_name(self):
        """symbol_name(mac_sptr self) -> std::string"""
        return _plc_swig.mac_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(mac_sptr self) -> io_signature_sptr"""
        return _plc_swig.mac_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(mac_sptr self) -> io_signature_sptr"""
        return _plc_swig.mac_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(mac_sptr self) -> long"""
        return _plc_swig.mac_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(mac_sptr self) -> basic_block_sptr"""
        return _plc_swig.mac_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(mac_sptr self, int ninputs, int noutputs) -> bool"""
        return _plc_swig.mac_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(mac_sptr self) -> std::string"""
        return _plc_swig.mac_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(mac_sptr self, std::string name)"""
        return _plc_swig.mac_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(mac_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _plc_swig.mac_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(mac_sptr self) -> swig_int_ptr"""
        return _plc_swig.mac_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(mac_sptr self) -> swig_int_ptr"""
        return _plc_swig.mac_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(mac_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _plc_swig.mac_sptr_message_subscribers(self, *args, **kwargs)

mac_sptr_swigregister = _plc_swig.mac_sptr_swigregister
mac_sptr_swigregister(mac_sptr)

mac_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
mac = mac.make;

class plcp_receiver(object):
    """Proxy of C++ gr::plc::plcp_receiver class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """make(float threshold, unsigned int min_plateau, bool debug=False) -> plcp_receiver_sptr"""
        return _plc_swig.plcp_receiver_make(*args, **kwargs)

    make = staticmethod(make)
    __swig_destroy__ = _plc_swig.delete_plcp_receiver
    __del__ = lambda self : None;
plcp_receiver_swigregister = _plc_swig.plcp_receiver_swigregister
plcp_receiver_swigregister(plcp_receiver)

def plcp_receiver_make(*args, **kwargs):
  """plcp_receiver_make(float threshold, unsigned int min_plateau, bool debug=False) -> plcp_receiver_sptr"""
  return _plc_swig.plcp_receiver_make(*args, **kwargs)

class plcp_receiver_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::plc::plcp_receiver)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::plc::plcp_receiver)> self) -> plcp_receiver_sptr
        __init__(boost::shared_ptr<(gr::plc::plcp_receiver)> self, plcp_receiver p) -> plcp_receiver_sptr
        """
        this = _plc_swig.new_plcp_receiver_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(plcp_receiver_sptr self) -> plcp_receiver"""
        return _plc_swig.plcp_receiver_sptr___deref__(self)

    __swig_destroy__ = _plc_swig.delete_plcp_receiver_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """make(plcp_receiver_sptr self, float threshold, unsigned int min_plateau, bool debug=False) -> plcp_receiver_sptr"""
        return _plc_swig.plcp_receiver_sptr_make(self, *args, **kwargs)

    def history(self):
        """history(plcp_receiver_sptr self) -> unsigned int"""
        return _plc_swig.plcp_receiver_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(plcp_receiver_sptr self, int which, int delay)
        declare_sample_delay(plcp_receiver_sptr self, unsigned int delay)
        """
        return _plc_swig.plcp_receiver_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(plcp_receiver_sptr self, int which) -> unsigned int"""
        return _plc_swig.plcp_receiver_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(plcp_receiver_sptr self) -> int"""
        return _plc_swig.plcp_receiver_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(plcp_receiver_sptr self) -> double"""
        return _plc_swig.plcp_receiver_sptr_relative_rate(self)

    def start(self):
        """start(plcp_receiver_sptr self) -> bool"""
        return _plc_swig.plcp_receiver_sptr_start(self)

    def stop(self):
        """stop(plcp_receiver_sptr self) -> bool"""
        return _plc_swig.plcp_receiver_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(plcp_receiver_sptr self, unsigned int which_input) -> uint64_t"""
        return _plc_swig.plcp_receiver_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(plcp_receiver_sptr self, unsigned int which_output) -> uint64_t"""
        return _plc_swig.plcp_receiver_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(plcp_receiver_sptr self) -> int"""
        return _plc_swig.plcp_receiver_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(plcp_receiver_sptr self, int m)"""
        return _plc_swig.plcp_receiver_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(plcp_receiver_sptr self)"""
        return _plc_swig.plcp_receiver_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(plcp_receiver_sptr self) -> bool"""
        return _plc_swig.plcp_receiver_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(plcp_receiver_sptr self, int m)"""
        return _plc_swig.plcp_receiver_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(plcp_receiver_sptr self) -> int"""
        return _plc_swig.plcp_receiver_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(plcp_receiver_sptr self, int i) -> long"""
        return _plc_swig.plcp_receiver_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(plcp_receiver_sptr self, long max_output_buffer)
        set_max_output_buffer(plcp_receiver_sptr self, int port, long max_output_buffer)
        """
        return _plc_swig.plcp_receiver_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(plcp_receiver_sptr self, int i) -> long"""
        return _plc_swig.plcp_receiver_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(plcp_receiver_sptr self, long min_output_buffer)
        set_min_output_buffer(plcp_receiver_sptr self, int port, long min_output_buffer)
        """
        return _plc_swig.plcp_receiver_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(plcp_receiver_sptr self, int which) -> float
        pc_input_buffers_full(plcp_receiver_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_receiver_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(plcp_receiver_sptr self, int which) -> float
        pc_input_buffers_full_avg(plcp_receiver_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_receiver_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(plcp_receiver_sptr self, int which) -> float
        pc_input_buffers_full_var(plcp_receiver_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_receiver_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(plcp_receiver_sptr self, int which) -> float
        pc_output_buffers_full(plcp_receiver_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_receiver_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(plcp_receiver_sptr self, int which) -> float
        pc_output_buffers_full_avg(plcp_receiver_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_receiver_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(plcp_receiver_sptr self, int which) -> float
        pc_output_buffers_full_var(plcp_receiver_sptr self) -> pmt_vector_float
        """
        return _plc_swig.plcp_receiver_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(plcp_receiver_sptr self) -> float"""
        return _plc_swig.plcp_receiver_sptr_pc_work_time_total(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(plcp_receiver_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _plc_swig.plcp_receiver_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(plcp_receiver_sptr self)"""
        return _plc_swig.plcp_receiver_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(plcp_receiver_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _plc_swig.plcp_receiver_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(plcp_receiver_sptr self) -> int"""
        return _plc_swig.plcp_receiver_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(plcp_receiver_sptr self) -> int"""
        return _plc_swig.plcp_receiver_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(plcp_receiver_sptr self, int priority) -> int"""
        return _plc_swig.plcp_receiver_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(plcp_receiver_sptr self) -> std::string"""
        return _plc_swig.plcp_receiver_sptr_name(self)

    def symbol_name(self):
        """symbol_name(plcp_receiver_sptr self) -> std::string"""
        return _plc_swig.plcp_receiver_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(plcp_receiver_sptr self) -> io_signature_sptr"""
        return _plc_swig.plcp_receiver_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(plcp_receiver_sptr self) -> io_signature_sptr"""
        return _plc_swig.plcp_receiver_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(plcp_receiver_sptr self) -> long"""
        return _plc_swig.plcp_receiver_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(plcp_receiver_sptr self) -> basic_block_sptr"""
        return _plc_swig.plcp_receiver_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(plcp_receiver_sptr self, int ninputs, int noutputs) -> bool"""
        return _plc_swig.plcp_receiver_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(plcp_receiver_sptr self) -> std::string"""
        return _plc_swig.plcp_receiver_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(plcp_receiver_sptr self, std::string name)"""
        return _plc_swig.plcp_receiver_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(plcp_receiver_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _plc_swig.plcp_receiver_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(plcp_receiver_sptr self) -> swig_int_ptr"""
        return _plc_swig.plcp_receiver_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(plcp_receiver_sptr self) -> swig_int_ptr"""
        return _plc_swig.plcp_receiver_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(plcp_receiver_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _plc_swig.plcp_receiver_sptr_message_subscribers(self, *args, **kwargs)

plcp_receiver_sptr_swigregister = _plc_swig.plcp_receiver_sptr_swigregister
plcp_receiver_sptr_swigregister(plcp_receiver_sptr)

plcp_receiver_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
plcp_receiver = plcp_receiver.make;



